export const sanitizationConfig = {
  allowedTags: [
    'a',
    'abbr',
    'address',
    'article',
    'aside',
    'b',
    'bdi',
    'bdo',
    'blockquote',
    'br',
    'caption',
    'cite',
    'code',
    'col',
    'colgroup',
    'data',
    'dd',
    'dfn',
    'div',
    'dl',
    'dt',
    'em',
    'figcaption',
    'figure',
    'footer',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'header',
    'hgroup',
    'hr',
    'i',
    'iframe',
    'img',
    'kbd',
    'li',
    'main',
    'mark',
    'nav',
    'ol',
    'p',
    'pre',
    'q',
    'rb',
    'rp',
    'rt',
    'rtc',
    'ruby',
    's',
    'samp',
    'section',
    'small',
    'span',
    'strong',
    'sub',
    'sup',
    'table',
    'tbody',
    'td',
    'tfoot',
    'th',
    'thead',
    'time',
    'tr',
    'u',
    'ul',
    'var',
    'video',
    'wbr',
  ],
  disallowedTagsMode: 'discard',
  allowedAttributes: {
    a: ['href', 'name', 'target', 'class'],
    h1: ['class', 'style'],
    h2: ['class', 'style'],
    h3: ['class', 'style'],
    h4: ['class', 'style'],
    h5: ['class', 'style'],
    h6: ['class', 'style'],
    p: ['class', 'style'],
    span: ['class', 'style'],
    section: ['class'],
    article: ['class'],
    blockquote: ['class'],
    img: ['class', 'src', 'style', 'alt'],
    iframe: ['class', 'frameborder', 'allowfullscreen', 'src'],
    video: ['class', 'src'],
    ul: ['class', 'style'],
    ol: ['class', 'style'],
    li: ['class', 'style'],
  },
  selfClosing: [
    'img',
    'br',
    'hr',
    'area',
    'base',
    'basefont',
    'input',
    'link',
    'meta',
  ],
  allowedSchemes: ['https', 'mailto'],
  allowedSchemesByTag: {},
  allowedIframeHostnames: [
    'codepen.io',
    'codesandbox.io',
    'gist.github.com',

    'player.vimeo.com',
    'youtube.com',
    'instagram.com',

    'www.codepen.io',
    'www.codesandbox.io',
    'www.gist.github.com',

    'www.player.vimeo.com',
    'www.youtube.com',
    'www.instagram.com',
  ],
  allowedSchemesAppliedToAttributes: ['href', 'src', 'cite'],
  allowProtocolRelative: true,
  enforceHtmlBoundary: true,
}
